ignoredBuiltDependencies:
  - '@prisma/engines'
  - prisma

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
